// Code generated via go generate from gen_incb.go. DO NOT EDIT.

package runeseg

// incbCodePoints are taken from
// https://www.unicode.org/Public/17.0.0/ucd/DerivedCoreProperties.txt
// on January 4, 2026. See https://www.unicode.org/license.html for the Unicode
// license agreement.
var incbCodePoints = [][3]int{
	{0x0300, 0x036F, prInCBExtend},      // Mn [112] COMBINING GRAVE ACCENT..COMBINING LATIN SMALL LETTER X
	{0x0483, 0x0487, prInCBExtend},      // Mn   [5] COMBINING CYRILLIC TITLO..COMBINING CYRILLIC POKRYTIE
	{0x0488, 0x0489, prInCBExtend},      // Me   [2] COMBINING CYRILLIC HUNDRED THOUSANDS SIGN..COMBINING CYRILLIC MILLIONS SIGN
	{0x0591, 0x05BD, prInCBExtend},      // Mn  [45] HEBREW ACCENT ETNAHTA..HEBREW POINT METEG
	{0x05BF, 0x05BF, prInCBExtend},      // Mn       HEBREW POINT RAFE
	{0x05C1, 0x05C2, prInCBExtend},      // Mn   [2] HEBREW POINT SHIN DOT..HEBREW POINT SIN DOT
	{0x05C4, 0x05C5, prInCBExtend},      // Mn   [2] HEBREW MARK UPPER DOT..HEBREW MARK LOWER DOT
	{0x05C7, 0x05C7, prInCBExtend},      // Mn       HEBREW POINT QAMATS QATAN
	{0x0610, 0x061A, prInCBExtend},      // Mn  [11] ARABIC SIGN SALLALLAHOU ALAYHE WASSALLAM..ARABIC SMALL KASRA
	{0x064B, 0x065F, prInCBExtend},      // Mn  [21] ARABIC FATHATAN..ARABIC WAVY HAMZA BELOW
	{0x0670, 0x0670, prInCBExtend},      // Mn       ARABIC LETTER SUPERSCRIPT ALEF
	{0x06D6, 0x06DC, prInCBExtend},      // Mn   [7] ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA..ARABIC SMALL HIGH SEEN
	{0x06DF, 0x06E4, prInCBExtend},      // Mn   [6] ARABIC SMALL HIGH ROUNDED ZERO..ARABIC SMALL HIGH MADDA
	{0x06E7, 0x06E8, prInCBExtend},      // Mn   [2] ARABIC SMALL HIGH YEH..ARABIC SMALL HIGH NOON
	{0x06EA, 0x06ED, prInCBExtend},      // Mn   [4] ARABIC EMPTY CENTRE LOW STOP..ARABIC SMALL LOW MEEM
	{0x0711, 0x0711, prInCBExtend},      // Mn       SYRIAC LETTER SUPERSCRIPT ALAPH
	{0x0730, 0x074A, prInCBExtend},      // Mn  [27] SYRIAC PTHAHA ABOVE..SYRIAC BARREKH
	{0x07A6, 0x07B0, prInCBExtend},      // Mn  [11] THAANA ABAFILI..THAANA SUKUN
	{0x07EB, 0x07F3, prInCBExtend},      // Mn   [9] NKO COMBINING SHORT HIGH TONE..NKO COMBINING DOUBLE DOT ABOVE
	{0x07FD, 0x07FD, prInCBExtend},      // Mn       NKO DANTAYALAN
	{0x0816, 0x0819, prInCBExtend},      // Mn   [4] SAMARITAN MARK IN..SAMARITAN MARK DAGESH
	{0x081B, 0x0823, prInCBExtend},      // Mn   [9] SAMARITAN MARK EPENTHETIC YUT..SAMARITAN VOWEL SIGN A
	{0x0825, 0x0827, prInCBExtend},      // Mn   [3] SAMARITAN VOWEL SIGN SHORT A..SAMARITAN VOWEL SIGN U
	{0x0829, 0x082D, prInCBExtend},      // Mn   [5] SAMARITAN VOWEL SIGN LONG I..SAMARITAN MARK NEQUDAA
	{0x0859, 0x085B, prInCBExtend},      // Mn   [3] MANDAIC AFFRICATION MARK..MANDAIC GEMINATION MARK
	{0x0897, 0x089F, prInCBExtend},      // Mn   [9] ARABIC PEPET..ARABIC HALF MADDA OVER MADDA
	{0x08CA, 0x08E1, prInCBExtend},      // Mn  [24] ARABIC SMALL HIGH FARSI YEH..ARABIC SMALL HIGH SIGN SAFHA
	{0x08E3, 0x0902, prInCBExtend},      // Mn  [32] ARABIC TURNED DAMMA BELOW..DEVANAGARI SIGN ANUSVARA
	{0x0915, 0x0939, prInCBConsonant},   // Lo  [37] DEVANAGARI LETTER KA..DEVANAGARI LETTER HA
	{0x093A, 0x093A, prInCBExtend},      // Mn       DEVANAGARI VOWEL SIGN OE
	{0x093C, 0x093C, prInCBExtend},      // Mn       DEVANAGARI SIGN NUKTA
	{0x0941, 0x0948, prInCBExtend},      // Mn   [8] DEVANAGARI VOWEL SIGN U..DEVANAGARI VOWEL SIGN AI
	{0x094D, 0x094D, prInCBLinker},      // Mn       DEVANAGARI SIGN VIRAMA
	{0x0951, 0x0957, prInCBExtend},      // Mn   [7] DEVANAGARI STRESS SIGN UDATTA..DEVANAGARI VOWEL SIGN UUE
	{0x0958, 0x095F, prInCBConsonant},   // Lo   [8] DEVANAGARI LETTER QA..DEVANAGARI LETTER YYA
	{0x0962, 0x0963, prInCBExtend},      // Mn   [2] DEVANAGARI VOWEL SIGN VOCALIC L..DEVANAGARI VOWEL SIGN VOCALIC LL
	{0x0978, 0x097F, prInCBConsonant},   // Lo   [8] DEVANAGARI LETTER MARWARI DDA..DEVANAGARI LETTER BBA
	{0x0981, 0x0981, prInCBExtend},      // Mn       BENGALI SIGN CANDRABINDU
	{0x0995, 0x09A8, prInCBConsonant},   // Lo  [20] BENGALI LETTER KA..BENGALI LETTER NA
	{0x09AA, 0x09B0, prInCBConsonant},   // Lo   [7] BENGALI LETTER PA..BENGALI LETTER RA
	{0x09B2, 0x09B2, prInCBConsonant},   // Lo       BENGALI LETTER LA
	{0x09B6, 0x09B9, prInCBConsonant},   // Lo   [4] BENGALI LETTER SHA..BENGALI LETTER HA
	{0x09BC, 0x09BC, prInCBExtend},      // Mn       BENGALI SIGN NUKTA
	{0x09BE, 0x09BE, prInCBExtend},      // Mc       BENGALI VOWEL SIGN AA
	{0x09C1, 0x09C4, prInCBExtend},      // Mn   [4] BENGALI VOWEL SIGN U..BENGALI VOWEL SIGN VOCALIC RR
	{0x09CD, 0x09CD, prInCBLinker},      // Mn       BENGALI SIGN VIRAMA
	{0x09D7, 0x09D7, prInCBExtend},      // Mc       BENGALI AU LENGTH MARK
	{0x09DC, 0x09DD, prInCBConsonant},   // Lo   [2] BENGALI LETTER RRA..BENGALI LETTER RHA
	{0x09DF, 0x09DF, prInCBConsonant},   // Lo       BENGALI LETTER YYA
	{0x09E2, 0x09E3, prInCBExtend},      // Mn   [2] BENGALI VOWEL SIGN VOCALIC L..BENGALI VOWEL SIGN VOCALIC LL
	{0x09F0, 0x09F1, prInCBConsonant},   // Lo   [2] BENGALI LETTER RA WITH MIDDLE DIAGONAL..BENGALI LETTER RA WITH LOWER DIAGONAL
	{0x09FE, 0x09FE, prInCBExtend},      // Mn       BENGALI SANDHI MARK
	{0x0A01, 0x0A02, prInCBExtend},      // Mn   [2] GURMUKHI SIGN ADAK BINDI..GURMUKHI SIGN BINDI
	{0x0A3C, 0x0A3C, prInCBExtend},      // Mn       GURMUKHI SIGN NUKTA
	{0x0A41, 0x0A42, prInCBExtend},      // Mn   [2] GURMUKHI VOWEL SIGN U..GURMUKHI VOWEL SIGN UU
	{0x0A47, 0x0A48, prInCBExtend},      // Mn   [2] GURMUKHI VOWEL SIGN EE..GURMUKHI VOWEL SIGN AI
	{0x0A4B, 0x0A4D, prInCBExtend},      // Mn   [3] GURMUKHI VOWEL SIGN OO..GURMUKHI SIGN VIRAMA
	{0x0A51, 0x0A51, prInCBExtend},      // Mn       GURMUKHI SIGN UDAAT
	{0x0A70, 0x0A71, prInCBExtend},      // Mn   [2] GURMUKHI TIPPI..GURMUKHI ADDAK
	{0x0A75, 0x0A75, prInCBExtend},      // Mn       GURMUKHI SIGN YAKASH
	{0x0A81, 0x0A82, prInCBExtend},      // Mn   [2] GUJARATI SIGN CANDRABINDU..GUJARATI SIGN ANUSVARA
	{0x0A95, 0x0AA8, prInCBConsonant},   // Lo  [20] GUJARATI LETTER KA..GUJARATI LETTER NA
	{0x0AAA, 0x0AB0, prInCBConsonant},   // Lo   [7] GUJARATI LETTER PA..GUJARATI LETTER RA
	{0x0AB2, 0x0AB3, prInCBConsonant},   // Lo   [2] GUJARATI LETTER LA..GUJARATI LETTER LLA
	{0x0AB5, 0x0AB9, prInCBConsonant},   // Lo   [5] GUJARATI LETTER VA..GUJARATI LETTER HA
	{0x0ABC, 0x0ABC, prInCBExtend},      // Mn       GUJARATI SIGN NUKTA
	{0x0AC1, 0x0AC5, prInCBExtend},      // Mn   [5] GUJARATI VOWEL SIGN U..GUJARATI VOWEL SIGN CANDRA E
	{0x0AC7, 0x0AC8, prInCBExtend},      // Mn   [2] GUJARATI VOWEL SIGN E..GUJARATI VOWEL SIGN AI
	{0x0ACD, 0x0ACD, prInCBLinker},      // Mn       GUJARATI SIGN VIRAMA
	{0x0AE2, 0x0AE3, prInCBExtend},      // Mn   [2] GUJARATI VOWEL SIGN VOCALIC L..GUJARATI VOWEL SIGN VOCALIC LL
	{0x0AF9, 0x0AF9, prInCBConsonant},   // Lo       GUJARATI LETTER ZHA
	{0x0AFA, 0x0AFF, prInCBExtend},      // Mn   [6] GUJARATI SIGN SUKUN..GUJARATI SIGN TWO-CIRCLE NUKTA ABOVE
	{0x0B01, 0x0B01, prInCBExtend},      // Mn       ORIYA SIGN CANDRABINDU
	{0x0B15, 0x0B28, prInCBConsonant},   // Lo  [20] ORIYA LETTER KA..ORIYA LETTER NA
	{0x0B2A, 0x0B30, prInCBConsonant},   // Lo   [7] ORIYA LETTER PA..ORIYA LETTER RA
	{0x0B32, 0x0B33, prInCBConsonant},   // Lo   [2] ORIYA LETTER LA..ORIYA LETTER LLA
	{0x0B35, 0x0B39, prInCBConsonant},   // Lo   [5] ORIYA LETTER VA..ORIYA LETTER HA
	{0x0B3C, 0x0B3C, prInCBExtend},      // Mn       ORIYA SIGN NUKTA
	{0x0B3E, 0x0B3E, prInCBExtend},      // Mc       ORIYA VOWEL SIGN AA
	{0x0B3F, 0x0B3F, prInCBExtend},      // Mn       ORIYA VOWEL SIGN I
	{0x0B41, 0x0B44, prInCBExtend},      // Mn   [4] ORIYA VOWEL SIGN U..ORIYA VOWEL SIGN VOCALIC RR
	{0x0B4D, 0x0B4D, prInCBLinker},      // Mn       ORIYA SIGN VIRAMA
	{0x0B55, 0x0B56, prInCBExtend},      // Mn   [2] ORIYA SIGN OVERLINE..ORIYA AI LENGTH MARK
	{0x0B57, 0x0B57, prInCBExtend},      // Mc       ORIYA AU LENGTH MARK
	{0x0B5C, 0x0B5D, prInCBConsonant},   // Lo   [2] ORIYA LETTER RRA..ORIYA LETTER RHA
	{0x0B5F, 0x0B5F, prInCBConsonant},   // Lo       ORIYA LETTER YYA
	{0x0B62, 0x0B63, prInCBExtend},      // Mn   [2] ORIYA VOWEL SIGN VOCALIC L..ORIYA VOWEL SIGN VOCALIC LL
	{0x0B71, 0x0B71, prInCBConsonant},   // Lo       ORIYA LETTER WA
	{0x0B82, 0x0B82, prInCBExtend},      // Mn       TAMIL SIGN ANUSVARA
	{0x0BBE, 0x0BBE, prInCBExtend},      // Mc       TAMIL VOWEL SIGN AA
	{0x0BC0, 0x0BC0, prInCBExtend},      // Mn       TAMIL VOWEL SIGN II
	{0x0BCD, 0x0BCD, prInCBExtend},      // Mn       TAMIL SIGN VIRAMA
	{0x0BD7, 0x0BD7, prInCBExtend},      // Mc       TAMIL AU LENGTH MARK
	{0x0C00, 0x0C00, prInCBExtend},      // Mn       TELUGU SIGN COMBINING CANDRABINDU ABOVE
	{0x0C04, 0x0C04, prInCBExtend},      // Mn       TELUGU SIGN COMBINING ANUSVARA ABOVE
	{0x0C15, 0x0C28, prInCBConsonant},   // Lo  [20] TELUGU LETTER KA..TELUGU LETTER NA
	{0x0C2A, 0x0C39, prInCBConsonant},   // Lo  [16] TELUGU LETTER PA..TELUGU LETTER HA
	{0x0C3C, 0x0C3C, prInCBExtend},      // Mn       TELUGU SIGN NUKTA
	{0x0C3E, 0x0C40, prInCBExtend},      // Mn   [3] TELUGU VOWEL SIGN AA..TELUGU VOWEL SIGN II
	{0x0C46, 0x0C48, prInCBExtend},      // Mn   [3] TELUGU VOWEL SIGN E..TELUGU VOWEL SIGN AI
	{0x0C4A, 0x0C4C, prInCBExtend},      // Mn   [3] TELUGU VOWEL SIGN O..TELUGU VOWEL SIGN AU
	{0x0C4D, 0x0C4D, prInCBLinker},      // Mn       TELUGU SIGN VIRAMA
	{0x0C55, 0x0C56, prInCBExtend},      // Mn   [2] TELUGU LENGTH MARK..TELUGU AI LENGTH MARK
	{0x0C58, 0x0C5A, prInCBConsonant},   // Lo   [3] TELUGU LETTER TSA..TELUGU LETTER RRRA
	{0x0C62, 0x0C63, prInCBExtend},      // Mn   [2] TELUGU VOWEL SIGN VOCALIC L..TELUGU VOWEL SIGN VOCALIC LL
	{0x0C81, 0x0C81, prInCBExtend},      // Mn       KANNADA SIGN CANDRABINDU
	{0x0CBC, 0x0CBC, prInCBExtend},      // Mn       KANNADA SIGN NUKTA
	{0x0CBF, 0x0CBF, prInCBExtend},      // Mn       KANNADA VOWEL SIGN I
	{0x0CC0, 0x0CC0, prInCBExtend},      // Mc       KANNADA VOWEL SIGN II
	{0x0CC2, 0x0CC2, prInCBExtend},      // Mc       KANNADA VOWEL SIGN UU
	{0x0CC6, 0x0CC6, prInCBExtend},      // Mn       KANNADA VOWEL SIGN E
	{0x0CC7, 0x0CC8, prInCBExtend},      // Mc   [2] KANNADA VOWEL SIGN EE..KANNADA VOWEL SIGN AI
	{0x0CCA, 0x0CCB, prInCBExtend},      // Mc   [2] KANNADA VOWEL SIGN O..KANNADA VOWEL SIGN OO
	{0x0CCC, 0x0CCD, prInCBExtend},      // Mn   [2] KANNADA VOWEL SIGN AU..KANNADA SIGN VIRAMA
	{0x0CD5, 0x0CD6, prInCBExtend},      // Mc   [2] KANNADA LENGTH MARK..KANNADA AI LENGTH MARK
	{0x0CE2, 0x0CE3, prInCBExtend},      // Mn   [2] KANNADA VOWEL SIGN VOCALIC L..KANNADA VOWEL SIGN VOCALIC LL
	{0x0D00, 0x0D01, prInCBExtend},      // Mn   [2] MALAYALAM SIGN COMBINING ANUSVARA ABOVE..MALAYALAM SIGN CANDRABINDU
	{0x0D15, 0x0D3A, prInCBConsonant},   // Lo  [38] MALAYALAM LETTER KA..MALAYALAM LETTER TTTA
	{0x0D3B, 0x0D3C, prInCBExtend},      // Mn   [2] MALAYALAM SIGN VERTICAL BAR VIRAMA..MALAYALAM SIGN CIRCULAR VIRAMA
	{0x0D3E, 0x0D3E, prInCBExtend},      // Mc       MALAYALAM VOWEL SIGN AA
	{0x0D41, 0x0D44, prInCBExtend},      // Mn   [4] MALAYALAM VOWEL SIGN U..MALAYALAM VOWEL SIGN VOCALIC RR
	{0x0D4D, 0x0D4D, prInCBLinker},      // Mn       MALAYALAM SIGN VIRAMA
	{0x0D57, 0x0D57, prInCBExtend},      // Mc       MALAYALAM AU LENGTH MARK
	{0x0D62, 0x0D63, prInCBExtend},      // Mn   [2] MALAYALAM VOWEL SIGN VOCALIC L..MALAYALAM VOWEL SIGN VOCALIC LL
	{0x0D81, 0x0D81, prInCBExtend},      // Mn       SINHALA SIGN CANDRABINDU
	{0x0DCA, 0x0DCA, prInCBExtend},      // Mn       SINHALA SIGN AL-LAKUNA
	{0x0DCF, 0x0DCF, prInCBExtend},      // Mc       SINHALA VOWEL SIGN AELA-PILLA
	{0x0DD2, 0x0DD4, prInCBExtend},      // Mn   [3] SINHALA VOWEL SIGN KETTI IS-PILLA..SINHALA VOWEL SIGN KETTI PAA-PILLA
	{0x0DD6, 0x0DD6, prInCBExtend},      // Mn       SINHALA VOWEL SIGN DIGA PAA-PILLA
	{0x0DDF, 0x0DDF, prInCBExtend},      // Mc       SINHALA VOWEL SIGN GAYANUKITTA
	{0x0E31, 0x0E31, prInCBExtend},      // Mn       THAI CHARACTER MAI HAN-AKAT
	{0x0E34, 0x0E3A, prInCBExtend},      // Mn   [7] THAI CHARACTER SARA I..THAI CHARACTER PHINTHU
	{0x0E47, 0x0E4E, prInCBExtend},      // Mn   [8] THAI CHARACTER MAITAIKHU..THAI CHARACTER YAMAKKAN
	{0x0EB1, 0x0EB1, prInCBExtend},      // Mn       LAO VOWEL SIGN MAI KAN
	{0x0EB4, 0x0EBC, prInCBExtend},      // Mn   [9] LAO VOWEL SIGN I..LAO SEMIVOWEL SIGN LO
	{0x0EC8, 0x0ECE, prInCBExtend},      // Mn   [7] LAO TONE MAI EK..LAO YAMAKKAN
	{0x0F18, 0x0F19, prInCBExtend},      // Mn   [2] TIBETAN ASTROLOGICAL SIGN -KHYUD PA..TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS
	{0x0F35, 0x0F35, prInCBExtend},      // Mn       TIBETAN MARK NGAS BZUNG NYI ZLA
	{0x0F37, 0x0F37, prInCBExtend},      // Mn       TIBETAN MARK NGAS BZUNG SGOR RTAGS
	{0x0F39, 0x0F39, prInCBExtend},      // Mn       TIBETAN MARK TSA -PHRU
	{0x0F71, 0x0F7E, prInCBExtend},      // Mn  [14] TIBETAN VOWEL SIGN AA..TIBETAN SIGN RJES SU NGA RO
	{0x0F80, 0x0F84, prInCBExtend},      // Mn   [5] TIBETAN VOWEL SIGN REVERSED I..TIBETAN MARK HALANTA
	{0x0F86, 0x0F87, prInCBExtend},      // Mn   [2] TIBETAN SIGN LCI RTAGS..TIBETAN SIGN YANG RTAGS
	{0x0F8D, 0x0F97, prInCBExtend},      // Mn  [11] TIBETAN SUBJOINED SIGN LCE TSA CAN..TIBETAN SUBJOINED LETTER JA
	{0x0F99, 0x0FBC, prInCBExtend},      // Mn  [36] TIBETAN SUBJOINED LETTER NYA..TIBETAN SUBJOINED LETTER FIXED-FORM RA
	{0x0FC6, 0x0FC6, prInCBExtend},      // Mn       TIBETAN SYMBOL PADMA GDAN
	{0x1000, 0x102A, prInCBConsonant},   // Lo  [43] MYANMAR LETTER KA..MYANMAR LETTER AU
	{0x102D, 0x1030, prInCBExtend},      // Mn   [4] MYANMAR VOWEL SIGN I..MYANMAR VOWEL SIGN UU
	{0x1032, 0x1037, prInCBExtend},      // Mn   [6] MYANMAR VOWEL SIGN AI..MYANMAR SIGN DOT BELOW
	{0x1039, 0x1039, prInCBLinker},      // Mn       MYANMAR SIGN VIRAMA
	{0x103A, 0x103A, prInCBExtend},      // Mn       MYANMAR SIGN ASAT
	{0x103D, 0x103E, prInCBExtend},      // Mn   [2] MYANMAR CONSONANT SIGN MEDIAL WA..MYANMAR CONSONANT SIGN MEDIAL HA
	{0x103F, 0x103F, prInCBConsonant},   // Lo       MYANMAR LETTER GREAT SA
	{0x1050, 0x1055, prInCBConsonant},   // Lo   [6] MYANMAR LETTER SHA..MYANMAR LETTER VOCALIC LL
	{0x1058, 0x1059, prInCBExtend},      // Mn   [2] MYANMAR VOWEL SIGN VOCALIC L..MYANMAR VOWEL SIGN VOCALIC LL
	{0x105A, 0x105D, prInCBConsonant},   // Lo   [4] MYANMAR LETTER MON NGA..MYANMAR LETTER MON BBE
	{0x105E, 0x1060, prInCBExtend},      // Mn   [3] MYANMAR CONSONANT SIGN MON MEDIAL NA..MYANMAR CONSONANT SIGN MON MEDIAL LA
	{0x1061, 0x1061, prInCBConsonant},   // Lo       MYANMAR LETTER SGAW KAREN SHA
	{0x1065, 0x1066, prInCBConsonant},   // Lo   [2] MYANMAR LETTER WESTERN PWO KAREN THA..MYANMAR LETTER WESTERN PWO KAREN PWA
	{0x106E, 0x1070, prInCBConsonant},   // Lo   [3] MYANMAR LETTER EASTERN PWO KAREN NNA..MYANMAR LETTER EASTERN PWO KAREN GHWA
	{0x1071, 0x1074, prInCBExtend},      // Mn   [4] MYANMAR VOWEL SIGN GEBA KAREN I..MYANMAR VOWEL SIGN KAYAH EE
	{0x1075, 0x1081, prInCBConsonant},   // Lo  [13] MYANMAR LETTER SHAN KA..MYANMAR LETTER SHAN HA
	{0x1082, 0x1082, prInCBExtend},      // Mn       MYANMAR CONSONANT SIGN SHAN MEDIAL WA
	{0x1085, 0x1086, prInCBExtend},      // Mn   [2] MYANMAR VOWEL SIGN SHAN E ABOVE..MYANMAR VOWEL SIGN SHAN FINAL Y
	{0x108D, 0x108D, prInCBExtend},      // Mn       MYANMAR SIGN SHAN COUNCIL EMPHATIC TONE
	{0x108E, 0x108E, prInCBConsonant},   // Lo       MYANMAR LETTER RUMAI PALAUNG FA
	{0x109D, 0x109D, prInCBExtend},      // Mn       MYANMAR VOWEL SIGN AITON AI
	{0x135D, 0x135F, prInCBExtend},      // Mn   [3] ETHIOPIC COMBINING GEMINATION AND VOWEL LENGTH MARK..ETHIOPIC COMBINING GEMINATION MARK
	{0x1712, 0x1714, prInCBExtend},      // Mn   [3] TAGALOG VOWEL SIGN I..TAGALOG SIGN VIRAMA
	{0x1715, 0x1715, prInCBExtend},      // Mc       TAGALOG SIGN PAMUDPOD
	{0x1732, 0x1733, prInCBExtend},      // Mn   [2] HANUNOO VOWEL SIGN I..HANUNOO VOWEL SIGN U
	{0x1734, 0x1734, prInCBExtend},      // Mc       HANUNOO SIGN PAMUDPOD
	{0x1752, 0x1753, prInCBExtend},      // Mn   [2] BUHID VOWEL SIGN I..BUHID VOWEL SIGN U
	{0x1772, 0x1773, prInCBExtend},      // Mn   [2] TAGBANWA VOWEL SIGN I..TAGBANWA VOWEL SIGN U
	{0x1780, 0x17B3, prInCBConsonant},   // Lo  [52] KHMER LETTER KA..KHMER INDEPENDENT VOWEL QAU
	{0x17B4, 0x17B5, prInCBExtend},      // Mn   [2] KHMER VOWEL INHERENT AQ..KHMER VOWEL INHERENT AA
	{0x17B7, 0x17BD, prInCBExtend},      // Mn   [7] KHMER VOWEL SIGN I..KHMER VOWEL SIGN UA
	{0x17C6, 0x17C6, prInCBExtend},      // Mn       KHMER SIGN NIKAHIT
	{0x17C9, 0x17D1, prInCBExtend},      // Mn   [9] KHMER SIGN MUUSIKATOAN..KHMER SIGN VIRIAM
	{0x17D2, 0x17D2, prInCBLinker},      // Mn       KHMER SIGN COENG
	{0x17D3, 0x17D3, prInCBExtend},      // Mn       KHMER SIGN BATHAMASAT
	{0x17DD, 0x17DD, prInCBExtend},      // Mn       KHMER SIGN ATTHACAN
	{0x180B, 0x180D, prInCBExtend},      // Mn   [3] MONGOLIAN FREE VARIATION SELECTOR ONE..MONGOLIAN FREE VARIATION SELECTOR THREE
	{0x180F, 0x180F, prInCBExtend},      // Mn       MONGOLIAN FREE VARIATION SELECTOR FOUR
	{0x1885, 0x1886, prInCBExtend},      // Mn   [2] MONGOLIAN LETTER ALI GALI BALUDA..MONGOLIAN LETTER ALI GALI THREE BALUDA
	{0x18A9, 0x18A9, prInCBExtend},      // Mn       MONGOLIAN LETTER ALI GALI DAGALGA
	{0x1920, 0x1922, prInCBExtend},      // Mn   [3] LIMBU VOWEL SIGN A..LIMBU VOWEL SIGN U
	{0x1927, 0x1928, prInCBExtend},      // Mn   [2] LIMBU VOWEL SIGN E..LIMBU VOWEL SIGN O
	{0x1932, 0x1932, prInCBExtend},      // Mn       LIMBU SMALL LETTER ANUSVARA
	{0x1939, 0x193B, prInCBExtend},      // Mn   [3] LIMBU SIGN MUKPHRENG..LIMBU SIGN SA-I
	{0x1A17, 0x1A18, prInCBExtend},      // Mn   [2] BUGINESE VOWEL SIGN I..BUGINESE VOWEL SIGN U
	{0x1A1B, 0x1A1B, prInCBExtend},      // Mn       BUGINESE VOWEL SIGN AE
	{0x1A20, 0x1A54, prInCBConsonant},   // Lo  [53] TAI THAM LETTER HIGH KA..TAI THAM LETTER GREAT SA
	{0x1A56, 0x1A56, prInCBExtend},      // Mn       TAI THAM CONSONANT SIGN MEDIAL LA
	{0x1A58, 0x1A5E, prInCBExtend},      // Mn   [7] TAI THAM SIGN MAI KANG LAI..TAI THAM CONSONANT SIGN SA
	{0x1A60, 0x1A60, prInCBLinker},      // Mn       TAI THAM SIGN SAKOT
	{0x1A62, 0x1A62, prInCBExtend},      // Mn       TAI THAM VOWEL SIGN MAI SAT
	{0x1A65, 0x1A6C, prInCBExtend},      // Mn   [8] TAI THAM VOWEL SIGN I..TAI THAM VOWEL SIGN OA BELOW
	{0x1A73, 0x1A7C, prInCBExtend},      // Mn  [10] TAI THAM VOWEL SIGN OA ABOVE..TAI THAM SIGN KHUEN-LUE KARAN
	{0x1A7F, 0x1A7F, prInCBExtend},      // Mn       TAI THAM COMBINING CRYPTOGRAMMIC DOT
	{0x1AB0, 0x1ABD, prInCBExtend},      // Mn  [14] COMBINING DOUBLED CIRCUMFLEX ACCENT..COMBINING PARENTHESES BELOW
	{0x1ABE, 0x1ABE, prInCBExtend},      // Me       COMBINING PARENTHESES OVERLAY
	{0x1ABF, 0x1ADD, prInCBExtend},      // Mn  [31] COMBINING LATIN SMALL LETTER W BELOW..COMBINING DOT-AND-RING BELOW
	{0x1AE0, 0x1AEB, prInCBExtend},      // Mn  [12] COMBINING LEFT TACK ABOVE..COMBINING DOUBLE RIGHTWARDS ARROW ABOVE
	{0x1B00, 0x1B03, prInCBExtend},      // Mn   [4] BALINESE SIGN ULU RICEM..BALINESE SIGN SURANG
	{0x1B0B, 0x1B0C, prInCBConsonant},   // Lo   [2] BALINESE LETTER RA REPA..BALINESE LETTER RA REPA TEDUNG
	{0x1B13, 0x1B33, prInCBConsonant},   // Lo  [33] BALINESE LETTER KA..BALINESE LETTER HA
	{0x1B34, 0x1B34, prInCBExtend},      // Mn       BALINESE SIGN REREKAN
	{0x1B35, 0x1B35, prInCBExtend},      // Mc       BALINESE VOWEL SIGN TEDUNG
	{0x1B36, 0x1B3A, prInCBExtend},      // Mn   [5] BALINESE VOWEL SIGN ULU..BALINESE VOWEL SIGN RA REPA
	{0x1B3B, 0x1B3B, prInCBExtend},      // Mc       BALINESE VOWEL SIGN RA REPA TEDUNG
	{0x1B3C, 0x1B3C, prInCBExtend},      // Mn       BALINESE VOWEL SIGN LA LENGA
	{0x1B3D, 0x1B3D, prInCBExtend},      // Mc       BALINESE VOWEL SIGN LA LENGA TEDUNG
	{0x1B42, 0x1B42, prInCBExtend},      // Mn       BALINESE VOWEL SIGN PEPET
	{0x1B43, 0x1B43, prInCBExtend},      // Mc       BALINESE VOWEL SIGN PEPET TEDUNG
	{0x1B44, 0x1B44, prInCBLinker},      // Mc       BALINESE ADEG ADEG
	{0x1B45, 0x1B4C, prInCBConsonant},   // Lo   [8] BALINESE LETTER KAF SASAK..BALINESE LETTER ARCHAIC JNYA
	{0x1B6B, 0x1B73, prInCBExtend},      // Mn   [9] BALINESE MUSICAL SYMBOL COMBINING TEGEH..BALINESE MUSICAL SYMBOL COMBINING GONG
	{0x1B80, 0x1B81, prInCBExtend},      // Mn   [2] SUNDANESE SIGN PANYECEK..SUNDANESE SIGN PANGLAYAR
	{0x1B83, 0x1BA0, prInCBConsonant},   // Lo  [30] SUNDANESE LETTER A..SUNDANESE LETTER HA
	{0x1BA2, 0x1BA5, prInCBExtend},      // Mn   [4] SUNDANESE CONSONANT SIGN PANYAKRA..SUNDANESE VOWEL SIGN PANYUKU
	{0x1BA8, 0x1BA9, prInCBExtend},      // Mn   [2] SUNDANESE VOWEL SIGN PAMEPET..SUNDANESE VOWEL SIGN PANEULEUNG
	{0x1BAA, 0x1BAA, prInCBExtend},      // Mc       SUNDANESE SIGN PAMAAEH
	{0x1BAB, 0x1BAB, prInCBLinker},      // Mn       SUNDANESE SIGN VIRAMA
	{0x1BAC, 0x1BAD, prInCBExtend},      // Mn   [2] SUNDANESE CONSONANT SIGN PASANGAN MA..SUNDANESE CONSONANT SIGN PASANGAN WA
	{0x1BAE, 0x1BAF, prInCBConsonant},   // Lo   [2] SUNDANESE LETTER KHA..SUNDANESE LETTER SYA
	{0x1BBB, 0x1BBD, prInCBConsonant},   // Lo   [3] SUNDANESE LETTER REU..SUNDANESE LETTER BHA
	{0x1BE6, 0x1BE6, prInCBExtend},      // Mn       BATAK SIGN TOMPI
	{0x1BE8, 0x1BE9, prInCBExtend},      // Mn   [2] BATAK VOWEL SIGN PAKPAK E..BATAK VOWEL SIGN EE
	{0x1BED, 0x1BED, prInCBExtend},      // Mn       BATAK VOWEL SIGN KARO O
	{0x1BEF, 0x1BF1, prInCBExtend},      // Mn   [3] BATAK VOWEL SIGN U FOR SIMALUNGUN SA..BATAK CONSONANT SIGN H
	{0x1BF2, 0x1BF3, prInCBExtend},      // Mc   [2] BATAK PANGOLAT..BATAK PANONGONAN
	{0x1C2C, 0x1C33, prInCBExtend},      // Mn   [8] LEPCHA VOWEL SIGN E..LEPCHA CONSONANT SIGN T
	{0x1C36, 0x1C37, prInCBExtend},      // Mn   [2] LEPCHA SIGN RAN..LEPCHA SIGN NUKTA
	{0x1CD0, 0x1CD2, prInCBExtend},      // Mn   [3] VEDIC TONE KARSHANA..VEDIC TONE PRENKHA
	{0x1CD4, 0x1CE0, prInCBExtend},      // Mn  [13] VEDIC SIGN YAJURVEDIC MIDLINE SVARITA..VEDIC TONE RIGVEDIC KASHMIRI INDEPENDENT SVARITA
	{0x1CE2, 0x1CE8, prInCBExtend},      // Mn   [7] VEDIC SIGN VISARGA SVARITA..VEDIC SIGN VISARGA ANUDATTA WITH TAIL
	{0x1CED, 0x1CED, prInCBExtend},      // Mn       VEDIC SIGN TIRYAK
	{0x1CF4, 0x1CF4, prInCBExtend},      // Mn       VEDIC TONE CANDRA ABOVE
	{0x1CF8, 0x1CF9, prInCBExtend},      // Mn   [2] VEDIC TONE RING ABOVE..VEDIC TONE DOUBLE RING ABOVE
	{0x1DC0, 0x1DFF, prInCBExtend},      // Mn  [64] COMBINING DOTTED GRAVE ACCENT..COMBINING RIGHT ARROWHEAD AND DOWN ARROWHEAD BELOW
	{0x200D, 0x200D, prInCBExtend},      // Cf       ZERO WIDTH JOINER
	{0x20D0, 0x20DC, prInCBExtend},      // Mn  [13] COMBINING LEFT HARPOON ABOVE..COMBINING FOUR DOTS ABOVE
	{0x20DD, 0x20E0, prInCBExtend},      // Me   [4] COMBINING ENCLOSING CIRCLE..COMBINING ENCLOSING CIRCLE BACKSLASH
	{0x20E1, 0x20E1, prInCBExtend},      // Mn       COMBINING LEFT RIGHT ARROW ABOVE
	{0x20E2, 0x20E4, prInCBExtend},      // Me   [3] COMBINING ENCLOSING SCREEN..COMBINING ENCLOSING UPWARD POINTING TRIANGLE
	{0x20E5, 0x20F0, prInCBExtend},      // Mn  [12] COMBINING REVERSE SOLIDUS OVERLAY..COMBINING ASTERISK ABOVE
	{0x2CEF, 0x2CF1, prInCBExtend},      // Mn   [3] COPTIC COMBINING NI ABOVE..COPTIC COMBINING SPIRITUS LENIS
	{0x2D7F, 0x2D7F, prInCBExtend},      // Mn       TIFINAGH CONSONANT JOINER
	{0x2DE0, 0x2DFF, prInCBExtend},      // Mn  [32] COMBINING CYRILLIC LETTER BE..COMBINING CYRILLIC LETTER IOTIFIED BIG YUS
	{0x302A, 0x302D, prInCBExtend},      // Mn   [4] IDEOGRAPHIC LEVEL TONE MARK..IDEOGRAPHIC ENTERING TONE MARK
	{0x302E, 0x302F, prInCBExtend},      // Mc   [2] HANGUL SINGLE DOT TONE MARK..HANGUL DOUBLE DOT TONE MARK
	{0x3099, 0x309A, prInCBExtend},      // Mn   [2] COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK..COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
	{0xA66F, 0xA66F, prInCBExtend},      // Mn       COMBINING CYRILLIC VZMET
	{0xA670, 0xA672, prInCBExtend},      // Me   [3] COMBINING CYRILLIC TEN MILLIONS SIGN..COMBINING CYRILLIC THOUSAND MILLIONS SIGN
	{0xA674, 0xA67D, prInCBExtend},      // Mn  [10] COMBINING CYRILLIC LETTER UKRAINIAN IE..COMBINING CYRILLIC PAYEROK
	{0xA69E, 0xA69F, prInCBExtend},      // Mn   [2] COMBINING CYRILLIC LETTER EF..COMBINING CYRILLIC LETTER IOTIFIED E
	{0xA6F0, 0xA6F1, prInCBExtend},      // Mn   [2] BAMUM COMBINING MARK KOQNDON..BAMUM COMBINING MARK TUKWENTIS
	{0xA802, 0xA802, prInCBExtend},      // Mn       SYLOTI NAGRI SIGN DVISVARA
	{0xA806, 0xA806, prInCBExtend},      // Mn       SYLOTI NAGRI SIGN HASANTA
	{0xA80B, 0xA80B, prInCBExtend},      // Mn       SYLOTI NAGRI SIGN ANUSVARA
	{0xA825, 0xA826, prInCBExtend},      // Mn   [2] SYLOTI NAGRI VOWEL SIGN U..SYLOTI NAGRI VOWEL SIGN E
	{0xA82C, 0xA82C, prInCBExtend},      // Mn       SYLOTI NAGRI SIGN ALTERNATE HASANTA
	{0xA8C4, 0xA8C5, prInCBExtend},      // Mn   [2] SAURASHTRA SIGN VIRAMA..SAURASHTRA SIGN CANDRABINDU
	{0xA8E0, 0xA8F1, prInCBExtend},      // Mn  [18] COMBINING DEVANAGARI DIGIT ZERO..COMBINING DEVANAGARI SIGN AVAGRAHA
	{0xA8FF, 0xA8FF, prInCBExtend},      // Mn       DEVANAGARI VOWEL SIGN AY
	{0xA926, 0xA92D, prInCBExtend},      // Mn   [8] KAYAH LI VOWEL UE..KAYAH LI TONE CALYA PLOPHU
	{0xA947, 0xA951, prInCBExtend},      // Mn  [11] REJANG VOWEL SIGN I..REJANG CONSONANT SIGN R
	{0xA953, 0xA953, prInCBExtend},      // Mc       REJANG VIRAMA
	{0xA980, 0xA982, prInCBExtend},      // Mn   [3] JAVANESE SIGN PANYANGGA..JAVANESE SIGN LAYAR
	{0xA989, 0xA98B, prInCBConsonant},   // Lo   [3] JAVANESE LETTER PA CEREK..JAVANESE LETTER NGA LELET RASWADI
	{0xA98F, 0xA9B2, prInCBConsonant},   // Lo  [36] JAVANESE LETTER KA..JAVANESE LETTER HA
	{0xA9B3, 0xA9B3, prInCBExtend},      // Mn       JAVANESE SIGN CECAK TELU
	{0xA9B6, 0xA9B9, prInCBExtend},      // Mn   [4] JAVANESE VOWEL SIGN WULU..JAVANESE VOWEL SIGN SUKU MENDUT
	{0xA9BC, 0xA9BD, prInCBExtend},      // Mn   [2] JAVANESE VOWEL SIGN PEPET..JAVANESE CONSONANT SIGN KERET
	{0xA9C0, 0xA9C0, prInCBLinker},      // Mc       JAVANESE PANGKON
	{0xA9E0, 0xA9E4, prInCBConsonant},   // Lo   [5] MYANMAR LETTER SHAN GHA..MYANMAR LETTER SHAN BHA
	{0xA9E5, 0xA9E5, prInCBExtend},      // Mn       MYANMAR SIGN SHAN SAW
	{0xA9E7, 0xA9EF, prInCBConsonant},   // Lo   [9] MYANMAR LETTER TAI LAING NYA..MYANMAR LETTER TAI LAING NNA
	{0xA9FA, 0xA9FE, prInCBConsonant},   // Lo   [5] MYANMAR LETTER TAI LAING LLA..MYANMAR LETTER TAI LAING BHA
	{0xAA29, 0xAA2E, prInCBExtend},      // Mn   [6] CHAM VOWEL SIGN AA..CHAM VOWEL SIGN OE
	{0xAA31, 0xAA32, prInCBExtend},      // Mn   [2] CHAM VOWEL SIGN AU..CHAM VOWEL SIGN UE
	{0xAA35, 0xAA36, prInCBExtend},      // Mn   [2] CHAM CONSONANT SIGN LA..CHAM CONSONANT SIGN WA
	{0xAA43, 0xAA43, prInCBExtend},      // Mn       CHAM CONSONANT SIGN FINAL NG
	{0xAA4C, 0xAA4C, prInCBExtend},      // Mn       CHAM CONSONANT SIGN FINAL M
	{0xAA60, 0xAA6F, prInCBConsonant},   // Lo  [16] MYANMAR LETTER KHAMTI GA..MYANMAR LETTER KHAMTI FA
	{0xAA71, 0xAA73, prInCBConsonant},   // Lo   [3] MYANMAR LETTER KHAMTI XA..MYANMAR LETTER KHAMTI RA
	{0xAA7A, 0xAA7A, prInCBConsonant},   // Lo       MYANMAR LETTER AITON RA
	{0xAA7C, 0xAA7C, prInCBExtend},      // Mn       MYANMAR SIGN TAI LAING TONE-2
	{0xAA7E, 0xAA7F, prInCBConsonant},   // Lo   [2] MYANMAR LETTER SHWE PALAUNG CHA..MYANMAR LETTER SHWE PALAUNG SHA
	{0xAAB0, 0xAAB0, prInCBExtend},      // Mn       TAI VIET MAI KANG
	{0xAAB2, 0xAAB4, prInCBExtend},      // Mn   [3] TAI VIET VOWEL I..TAI VIET VOWEL U
	{0xAAB7, 0xAAB8, prInCBExtend},      // Mn   [2] TAI VIET MAI KHIT..TAI VIET VOWEL IA
	{0xAABE, 0xAABF, prInCBExtend},      // Mn   [2] TAI VIET VOWEL AM..TAI VIET TONE MAI EK
	{0xAAC1, 0xAAC1, prInCBExtend},      // Mn       TAI VIET TONE MAI THO
	{0xAAE0, 0xAAEA, prInCBConsonant},   // Lo  [11] MEETEI MAYEK LETTER E..MEETEI MAYEK LETTER SSA
	{0xAAEC, 0xAAED, prInCBExtend},      // Mn   [2] MEETEI MAYEK VOWEL SIGN UU..MEETEI MAYEK VOWEL SIGN AAI
	{0xAAF6, 0xAAF6, prInCBLinker},      // Mn       MEETEI MAYEK VIRAMA
	{0xABC0, 0xABDA, prInCBConsonant},   // Lo  [27] MEETEI MAYEK LETTER KOK..MEETEI MAYEK LETTER BHAM
	{0xABE5, 0xABE5, prInCBExtend},      // Mn       MEETEI MAYEK VOWEL SIGN ANAP
	{0xABE8, 0xABE8, prInCBExtend},      // Mn       MEETEI MAYEK VOWEL SIGN UNAP
	{0xABED, 0xABED, prInCBExtend},      // Mn       MEETEI MAYEK APUN IYEK
	{0xFB1E, 0xFB1E, prInCBExtend},      // Mn       HEBREW POINT JUDEO-SPANISH VARIKA
	{0xFE00, 0xFE0F, prInCBExtend},      // Mn  [16] VARIATION SELECTOR-1..VARIATION SELECTOR-16
	{0xFE20, 0xFE2F, prInCBExtend},      // Mn  [16] COMBINING LIGATURE LEFT HALF..COMBINING CYRILLIC TITLO RIGHT HALF
	{0xFF9E, 0xFF9F, prInCBExtend},      // Lm   [2] HALFWIDTH KATAKANA VOICED SOUND MARK..HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
	{0x101FD, 0x101FD, prInCBExtend},    // Mn       PHAISTOS DISC SIGN COMBINING OBLIQUE STROKE
	{0x102E0, 0x102E0, prInCBExtend},    // Mn       COPTIC EPACT THOUSANDS MARK
	{0x10376, 0x1037A, prInCBExtend},    // Mn   [5] COMBINING OLD PERMIC LETTER AN..COMBINING OLD PERMIC LETTER SII
	{0x10A00, 0x10A00, prInCBConsonant}, // Lo       KHAROSHTHI LETTER A
	{0x10A01, 0x10A03, prInCBExtend},    // Mn   [3] KHAROSHTHI VOWEL SIGN I..KHAROSHTHI VOWEL SIGN VOCALIC R
	{0x10A05, 0x10A06, prInCBExtend},    // Mn   [2] KHAROSHTHI VOWEL SIGN E..KHAROSHTHI VOWEL SIGN O
	{0x10A0C, 0x10A0F, prInCBExtend},    // Mn   [4] KHAROSHTHI VOWEL LENGTH MARK..KHAROSHTHI SIGN VISARGA
	{0x10A10, 0x10A13, prInCBConsonant}, // Lo   [4] KHAROSHTHI LETTER KA..KHAROSHTHI LETTER GHA
	{0x10A15, 0x10A17, prInCBConsonant}, // Lo   [3] KHAROSHTHI LETTER CA..KHAROSHTHI LETTER JA
	{0x10A19, 0x10A35, prInCBConsonant}, // Lo  [29] KHAROSHTHI LETTER NYA..KHAROSHTHI LETTER VHA
	{0x10A38, 0x10A3A, prInCBExtend},    // Mn   [3] KHAROSHTHI SIGN BAR ABOVE..KHAROSHTHI SIGN DOT BELOW
	{0x10A3F, 0x10A3F, prInCBLinker},    // Mn       KHAROSHTHI VIRAMA
	{0x10AE5, 0x10AE6, prInCBExtend},    // Mn   [2] MANICHAEAN ABBREVIATION MARK ABOVE..MANICHAEAN ABBREVIATION MARK BELOW
	{0x10D24, 0x10D27, prInCBExtend},    // Mn   [4] HANIFI ROHINGYA SIGN HARBAHAY..HANIFI ROHINGYA SIGN TASSI
	{0x10D69, 0x10D6D, prInCBExtend},    // Mn   [5] GARAY VOWEL SIGN E..GARAY CONSONANT NASALIZATION MARK
	{0x10EAB, 0x10EAC, prInCBExtend},    // Mn   [2] YEZIDI COMBINING HAMZA MARK..YEZIDI COMBINING MADDA MARK
	{0x10EFA, 0x10EFF, prInCBExtend},    // Mn   [6] ARABIC DOUBLE VERTICAL BAR BELOW..ARABIC SMALL LOW WORD MADDA
	{0x10F46, 0x10F50, prInCBExtend},    // Mn  [11] SOGDIAN COMBINING DOT BELOW..SOGDIAN COMBINING STROKE BELOW
	{0x10F82, 0x10F85, prInCBExtend},    // Mn   [4] OLD UYGHUR COMBINING DOT ABOVE..OLD UYGHUR COMBINING TWO DOTS BELOW
	{0x11001, 0x11001, prInCBExtend},    // Mn       BRAHMI SIGN ANUSVARA
	{0x11038, 0x11046, prInCBExtend},    // Mn  [15] BRAHMI VOWEL SIGN AA..BRAHMI VIRAMA
	{0x11070, 0x11070, prInCBExtend},    // Mn       BRAHMI SIGN OLD TAMIL VIRAMA
	{0x11073, 0x11074, prInCBExtend},    // Mn   [2] BRAHMI VOWEL SIGN OLD TAMIL SHORT E..BRAHMI VOWEL SIGN OLD TAMIL SHORT O
	{0x1107F, 0x11081, prInCBExtend},    // Mn   [3] BRAHMI NUMBER JOINER..KAITHI SIGN ANUSVARA
	{0x110B3, 0x110B6, prInCBExtend},    // Mn   [4] KAITHI VOWEL SIGN U..KAITHI VOWEL SIGN AI
	{0x110B9, 0x110BA, prInCBExtend},    // Mn   [2] KAITHI SIGN VIRAMA..KAITHI SIGN NUKTA
	{0x110C2, 0x110C2, prInCBExtend},    // Mn       KAITHI VOWEL SIGN VOCALIC R
	{0x11100, 0x11102, prInCBExtend},    // Mn   [3] CHAKMA SIGN CANDRABINDU..CHAKMA SIGN VISARGA
	{0x11103, 0x11126, prInCBConsonant}, // Lo  [36] CHAKMA LETTER AA..CHAKMA LETTER HAA
	{0x11127, 0x1112B, prInCBExtend},    // Mn   [5] CHAKMA VOWEL SIGN A..CHAKMA VOWEL SIGN UU
	{0x1112D, 0x11132, prInCBExtend},    // Mn   [6] CHAKMA VOWEL SIGN AI..CHAKMA AU MARK
	{0x11133, 0x11133, prInCBLinker},    // Mn       CHAKMA VIRAMA
	{0x11134, 0x11134, prInCBExtend},    // Mn       CHAKMA MAAYYAA
	{0x11144, 0x11144, prInCBConsonant}, // Lo       CHAKMA LETTER LHAA
	{0x11147, 0x11147, prInCBConsonant}, // Lo       CHAKMA LETTER VAA
	{0x11173, 0x11173, prInCBExtend},    // Mn       MAHAJANI SIGN NUKTA
	{0x11180, 0x11181, prInCBExtend},    // Mn   [2] SHARADA SIGN CANDRABINDU..SHARADA SIGN ANUSVARA
	{0x111B6, 0x111BE, prInCBExtend},    // Mn   [9] SHARADA VOWEL SIGN U..SHARADA VOWEL SIGN O
	{0x111C0, 0x111C0, prInCBExtend},    // Mc       SHARADA SIGN VIRAMA
	{0x111C9, 0x111CC, prInCBExtend},    // Mn   [4] SHARADA SANDHI MARK..SHARADA EXTRA SHORT VOWEL MARK
	{0x111CF, 0x111CF, prInCBExtend},    // Mn       SHARADA SIGN INVERTED CANDRABINDU
	{0x1122F, 0x11231, prInCBExtend},    // Mn   [3] KHOJKI VOWEL SIGN U..KHOJKI VOWEL SIGN AI
	{0x11234, 0x11234, prInCBExtend},    // Mn       KHOJKI SIGN ANUSVARA
	{0x11235, 0x11235, prInCBExtend},    // Mc       KHOJKI SIGN VIRAMA
	{0x11236, 0x11237, prInCBExtend},    // Mn   [2] KHOJKI SIGN NUKTA..KHOJKI SIGN SHADDA
	{0x1123E, 0x1123E, prInCBExtend},    // Mn       KHOJKI SIGN SUKUN
	{0x11241, 0x11241, prInCBExtend},    // Mn       KHOJKI VOWEL SIGN VOCALIC R
	{0x112DF, 0x112DF, prInCBExtend},    // Mn       KHUDAWADI SIGN ANUSVARA
	{0x112E3, 0x112EA, prInCBExtend},    // Mn   [8] KHUDAWADI VOWEL SIGN U..KHUDAWADI SIGN VIRAMA
	{0x11300, 0x11301, prInCBExtend},    // Mn   [2] GRANTHA SIGN COMBINING ANUSVARA ABOVE..GRANTHA SIGN CANDRABINDU
	{0x1133B, 0x1133C, prInCBExtend},    // Mn   [2] COMBINING BINDU BELOW..GRANTHA SIGN NUKTA
	{0x1133E, 0x1133E, prInCBExtend},    // Mc       GRANTHA VOWEL SIGN AA
	{0x11340, 0x11340, prInCBExtend},    // Mn       GRANTHA VOWEL SIGN II
	{0x1134D, 0x1134D, prInCBExtend},    // Mc       GRANTHA SIGN VIRAMA
	{0x11357, 0x11357, prInCBExtend},    // Mc       GRANTHA AU LENGTH MARK
	{0x11366, 0x1136C, prInCBExtend},    // Mn   [7] COMBINING GRANTHA DIGIT ZERO..COMBINING GRANTHA DIGIT SIX
	{0x11370, 0x11374, prInCBExtend},    // Mn   [5] COMBINING GRANTHA LETTER A..COMBINING GRANTHA LETTER PA
	{0x11380, 0x11389, prInCBConsonant}, // Lo  [10] TULU-TIGALARI LETTER A..TULU-TIGALARI LETTER VOCALIC LL
	{0x1138B, 0x1138B, prInCBConsonant}, // Lo       TULU-TIGALARI LETTER EE
	{0x1138E, 0x1138E, prInCBConsonant}, // Lo       TULU-TIGALARI LETTER AI
	{0x11390, 0x113B5, prInCBConsonant}, // Lo  [38] TULU-TIGALARI LETTER OO..TULU-TIGALARI LETTER LLLA
	{0x113B8, 0x113B8, prInCBExtend},    // Mc       TULU-TIGALARI VOWEL SIGN AA
	{0x113BB, 0x113C0, prInCBExtend},    // Mn   [6] TULU-TIGALARI VOWEL SIGN U..TULU-TIGALARI VOWEL SIGN VOCALIC LL
	{0x113C2, 0x113C2, prInCBExtend},    // Mc       TULU-TIGALARI VOWEL SIGN EE
	{0x113C5, 0x113C5, prInCBExtend},    // Mc       TULU-TIGALARI VOWEL SIGN AI
	{0x113C7, 0x113C9, prInCBExtend},    // Mc   [3] TULU-TIGALARI VOWEL SIGN OO..TULU-TIGALARI AU LENGTH MARK
	{0x113CE, 0x113CE, prInCBExtend},    // Mn       TULU-TIGALARI SIGN VIRAMA
	{0x113CF, 0x113CF, prInCBExtend},    // Mc       TULU-TIGALARI SIGN LOOPED VIRAMA
	{0x113D0, 0x113D0, prInCBLinker},    // Mn       TULU-TIGALARI CONJOINER
	{0x113D2, 0x113D2, prInCBExtend},    // Mn       TULU-TIGALARI GEMINATION MARK
	{0x113E1, 0x113E2, prInCBExtend},    // Mn   [2] TULU-TIGALARI VEDIC TONE SVARITA..TULU-TIGALARI VEDIC TONE ANUDATTA
	{0x11438, 0x1143F, prInCBExtend},    // Mn   [8] NEWA VOWEL SIGN U..NEWA VOWEL SIGN AI
	{0x11442, 0x11444, prInCBExtend},    // Mn   [3] NEWA SIGN VIRAMA..NEWA SIGN ANUSVARA
	{0x11446, 0x11446, prInCBExtend},    // Mn       NEWA SIGN NUKTA
	{0x1145E, 0x1145E, prInCBExtend},    // Mn       NEWA SANDHI MARK
	{0x114B0, 0x114B0, prInCBExtend},    // Mc       TIRHUTA VOWEL SIGN AA
	{0x114B3, 0x114B8, prInCBExtend},    // Mn   [6] TIRHUTA VOWEL SIGN U..TIRHUTA VOWEL SIGN VOCALIC LL
	{0x114BA, 0x114BA, prInCBExtend},    // Mn       TIRHUTA VOWEL SIGN SHORT E
	{0x114BD, 0x114BD, prInCBExtend},    // Mc       TIRHUTA VOWEL SIGN SHORT O
	{0x114BF, 0x114C0, prInCBExtend},    // Mn   [2] TIRHUTA SIGN CANDRABINDU..TIRHUTA SIGN ANUSVARA
	{0x114C2, 0x114C3, prInCBExtend},    // Mn   [2] TIRHUTA SIGN VIRAMA..TIRHUTA SIGN NUKTA
	{0x115AF, 0x115AF, prInCBExtend},    // Mc       SIDDHAM VOWEL SIGN AA
	{0x115B2, 0x115B5, prInCBExtend},    // Mn   [4] SIDDHAM VOWEL SIGN U..SIDDHAM VOWEL SIGN VOCALIC RR
	{0x115BC, 0x115BD, prInCBExtend},    // Mn   [2] SIDDHAM SIGN CANDRABINDU..SIDDHAM SIGN ANUSVARA
	{0x115BF, 0x115C0, prInCBExtend},    // Mn   [2] SIDDHAM SIGN VIRAMA..SIDDHAM SIGN NUKTA
	{0x115DC, 0x115DD, prInCBExtend},    // Mn   [2] SIDDHAM VOWEL SIGN ALTERNATE U..SIDDHAM VOWEL SIGN ALTERNATE UU
	{0x11633, 0x1163A, prInCBExtend},    // Mn   [8] MODI VOWEL SIGN U..MODI VOWEL SIGN AI
	{0x1163D, 0x1163D, prInCBExtend},    // Mn       MODI SIGN ANUSVARA
	{0x1163F, 0x11640, prInCBExtend},    // Mn   [2] MODI SIGN VIRAMA..MODI SIGN ARDHACANDRA
	{0x116AB, 0x116AB, prInCBExtend},    // Mn       TAKRI SIGN ANUSVARA
	{0x116AD, 0x116AD, prInCBExtend},    // Mn       TAKRI VOWEL SIGN AA
	{0x116B0, 0x116B5, prInCBExtend},    // Mn   [6] TAKRI VOWEL SIGN U..TAKRI VOWEL SIGN AU
	{0x116B6, 0x116B6, prInCBExtend},    // Mc       TAKRI SIGN VIRAMA
	{0x116B7, 0x116B7, prInCBExtend},    // Mn       TAKRI SIGN NUKTA
	{0x1171D, 0x1171D, prInCBExtend},    // Mn       AHOM CONSONANT SIGN MEDIAL LA
	{0x1171F, 0x1171F, prInCBExtend},    // Mn       AHOM CONSONANT SIGN MEDIAL LIGATING RA
	{0x11722, 0x11725, prInCBExtend},    // Mn   [4] AHOM VOWEL SIGN I..AHOM VOWEL SIGN UU
	{0x11727, 0x1172B, prInCBExtend},    // Mn   [5] AHOM VOWEL SIGN AW..AHOM SIGN KILLER
	{0x1182F, 0x11837, prInCBExtend},    // Mn   [9] DOGRA VOWEL SIGN U..DOGRA SIGN ANUSVARA
	{0x11839, 0x1183A, prInCBExtend},    // Mn   [2] DOGRA SIGN VIRAMA..DOGRA SIGN NUKTA
	{0x11900, 0x11906, prInCBConsonant}, // Lo   [7] DIVES AKURU LETTER A..DIVES AKURU LETTER E
	{0x11909, 0x11909, prInCBConsonant}, // Lo       DIVES AKURU LETTER O
	{0x1190C, 0x11913, prInCBConsonant}, // Lo   [8] DIVES AKURU LETTER KA..DIVES AKURU LETTER JA
	{0x11915, 0x11916, prInCBConsonant}, // Lo   [2] DIVES AKURU LETTER NYA..DIVES AKURU LETTER TTA
	{0x11918, 0x1192F, prInCBConsonant}, // Lo  [24] DIVES AKURU LETTER DDA..DIVES AKURU LETTER ZA
	{0x11930, 0x11930, prInCBExtend},    // Mc       DIVES AKURU VOWEL SIGN AA
	{0x1193B, 0x1193C, prInCBExtend},    // Mn   [2] DIVES AKURU SIGN ANUSVARA..DIVES AKURU SIGN CANDRABINDU
	{0x1193D, 0x1193D, prInCBExtend},    // Mc       DIVES AKURU SIGN HALANTA
	{0x1193E, 0x1193E, prInCBLinker},    // Mn       DIVES AKURU VIRAMA
	{0x11943, 0x11943, prInCBExtend},    // Mn       DIVES AKURU SIGN NUKTA
	{0x119D4, 0x119D7, prInCBExtend},    // Mn   [4] NANDINAGARI VOWEL SIGN U..NANDINAGARI VOWEL SIGN VOCALIC RR
	{0x119DA, 0x119DB, prInCBExtend},    // Mn   [2] NANDINAGARI VOWEL SIGN E..NANDINAGARI VOWEL SIGN AI
	{0x119E0, 0x119E0, prInCBExtend},    // Mn       NANDINAGARI SIGN VIRAMA
	{0x11A00, 0x11A00, prInCBConsonant}, // Lo       ZANABAZAR SQUARE LETTER A
	{0x11A01, 0x11A0A, prInCBExtend},    // Mn  [10] ZANABAZAR SQUARE VOWEL SIGN I..ZANABAZAR SQUARE VOWEL LENGTH MARK
	{0x11A0B, 0x11A32, prInCBConsonant}, // Lo  [40] ZANABAZAR SQUARE LETTER KA..ZANABAZAR SQUARE LETTER KSSA
	{0x11A33, 0x11A38, prInCBExtend},    // Mn   [6] ZANABAZAR SQUARE FINAL CONSONANT MARK..ZANABAZAR SQUARE SIGN ANUSVARA
	{0x11A3B, 0x11A3E, prInCBExtend},    // Mn   [4] ZANABAZAR SQUARE CLUSTER-FINAL LETTER YA..ZANABAZAR SQUARE CLUSTER-FINAL LETTER VA
	{0x11A47, 0x11A47, prInCBLinker},    // Mn       ZANABAZAR SQUARE SUBJOINER
	{0x11A50, 0x11A50, prInCBConsonant}, // Lo       SOYOMBO LETTER A
	{0x11A51, 0x11A56, prInCBExtend},    // Mn   [6] SOYOMBO VOWEL SIGN I..SOYOMBO VOWEL SIGN OE
	{0x11A59, 0x11A5B, prInCBExtend},    // Mn   [3] SOYOMBO VOWEL SIGN VOCALIC R..SOYOMBO VOWEL LENGTH MARK
	{0x11A5C, 0x11A83, prInCBConsonant}, // Lo  [40] SOYOMBO LETTER KA..SOYOMBO LETTER KSSA
	{0x11A8A, 0x11A96, prInCBExtend},    // Mn  [13] SOYOMBO FINAL CONSONANT SIGN G..SOYOMBO SIGN ANUSVARA
	{0x11A98, 0x11A98, prInCBExtend},    // Mn       SOYOMBO GEMINATION MARK
	{0x11A99, 0x11A99, prInCBLinker},    // Mn       SOYOMBO SUBJOINER
	{0x11B60, 0x11B60, prInCBExtend},    // Mn       SHARADA VOWEL SIGN OE
	{0x11B62, 0x11B64, prInCBExtend},    // Mn   [3] SHARADA VOWEL SIGN UE..SHARADA VOWEL SIGN SHORT E
	{0x11B66, 0x11B66, prInCBExtend},    // Mn       SHARADA VOWEL SIGN CANDRA E
	{0x11C30, 0x11C36, prInCBExtend},    // Mn   [7] BHAIKSUKI VOWEL SIGN I..BHAIKSUKI VOWEL SIGN VOCALIC L
	{0x11C38, 0x11C3D, prInCBExtend},    // Mn   [6] BHAIKSUKI VOWEL SIGN E..BHAIKSUKI SIGN ANUSVARA
	{0x11C3F, 0x11C3F, prInCBExtend},    // Mn       BHAIKSUKI SIGN VIRAMA
	{0x11C92, 0x11CA7, prInCBExtend},    // Mn  [22] MARCHEN SUBJOINED LETTER KA..MARCHEN SUBJOINED LETTER ZA
	{0x11CAA, 0x11CB0, prInCBExtend},    // Mn   [7] MARCHEN SUBJOINED LETTER RA..MARCHEN VOWEL SIGN AA
	{0x11CB2, 0x11CB3, prInCBExtend},    // Mn   [2] MARCHEN VOWEL SIGN U..MARCHEN VOWEL SIGN E
	{0x11CB5, 0x11CB6, prInCBExtend},    // Mn   [2] MARCHEN SIGN ANUSVARA..MARCHEN SIGN CANDRABINDU
	{0x11D31, 0x11D36, prInCBExtend},    // Mn   [6] MASARAM GONDI VOWEL SIGN AA..MASARAM GONDI VOWEL SIGN VOCALIC R
	{0x11D3A, 0x11D3A, prInCBExtend},    // Mn       MASARAM GONDI VOWEL SIGN E
	{0x11D3C, 0x11D3D, prInCBExtend},    // Mn   [2] MASARAM GONDI VOWEL SIGN AI..MASARAM GONDI VOWEL SIGN O
	{0x11D3F, 0x11D45, prInCBExtend},    // Mn   [7] MASARAM GONDI VOWEL SIGN AU..MASARAM GONDI VIRAMA
	{0x11D47, 0x11D47, prInCBExtend},    // Mn       MASARAM GONDI RA-KARA
	{0x11D90, 0x11D91, prInCBExtend},    // Mn   [2] GUNJALA GONDI VOWEL SIGN EE..GUNJALA GONDI VOWEL SIGN AI
	{0x11D95, 0x11D95, prInCBExtend},    // Mn       GUNJALA GONDI SIGN ANUSVARA
	{0x11D97, 0x11D97, prInCBExtend},    // Mn       GUNJALA GONDI VIRAMA
	{0x11EF3, 0x11EF4, prInCBExtend},    // Mn   [2] MAKASAR VOWEL SIGN I..MAKASAR VOWEL SIGN U
	{0x11F00, 0x11F01, prInCBExtend},    // Mn   [2] KAWI SIGN CANDRABINDU..KAWI SIGN ANUSVARA
	{0x11F04, 0x11F10, prInCBConsonant}, // Lo  [13] KAWI LETTER A..KAWI LETTER O
	{0x11F12, 0x11F33, prInCBConsonant}, // Lo  [34] KAWI LETTER KA..KAWI LETTER JNYA
	{0x11F36, 0x11F3A, prInCBExtend},    // Mn   [5] KAWI VOWEL SIGN I..KAWI VOWEL SIGN VOCALIC R
	{0x11F40, 0x11F40, prInCBExtend},    // Mn       KAWI VOWEL SIGN EU
	{0x11F41, 0x11F41, prInCBExtend},    // Mc       KAWI SIGN KILLER
	{0x11F42, 0x11F42, prInCBLinker},    // Mn       KAWI CONJOINER
	{0x11F5A, 0x11F5A, prInCBExtend},    // Mn       KAWI SIGN NUKTA
	{0x13440, 0x13440, prInCBExtend},    // Mn       EGYPTIAN HIEROGLYPH MIRROR HORIZONTALLY
	{0x13447, 0x13455, prInCBExtend},    // Mn  [15] EGYPTIAN HIEROGLYPH MODIFIER DAMAGED AT TOP START..EGYPTIAN HIEROGLYPH MODIFIER DAMAGED
	{0x1611E, 0x16129, prInCBExtend},    // Mn  [12] GURUNG KHEMA VOWEL SIGN AA..GURUNG KHEMA VOWEL LENGTH MARK
	{0x1612D, 0x1612F, prInCBExtend},    // Mn   [3] GURUNG KHEMA SIGN ANUSVARA..GURUNG KHEMA SIGN THOLHOMA
	{0x16AF0, 0x16AF4, prInCBExtend},    // Mn   [5] BASSA VAH COMBINING HIGH TONE..BASSA VAH COMBINING HIGH-LOW TONE
	{0x16B30, 0x16B36, prInCBExtend},    // Mn   [7] PAHAWH HMONG MARK CIM TUB..PAHAWH HMONG MARK CIM TAUM
	{0x16F4F, 0x16F4F, prInCBExtend},    // Mn       MIAO SIGN CONSONANT MODIFIER BAR
	{0x16F8F, 0x16F92, prInCBExtend},    // Mn   [4] MIAO TONE RIGHT..MIAO TONE BELOW
	{0x16FE4, 0x16FE4, prInCBExtend},    // Mn       KHITAN SMALL SCRIPT FILLER
	{0x16FF0, 0x16FF1, prInCBExtend},    // Mc   [2] VIETNAMESE ALTERNATE READING MARK CA..VIETNAMESE ALTERNATE READING MARK NHAY
	{0x1BC9D, 0x1BC9E, prInCBExtend},    // Mn   [2] DUPLOYAN THICK LETTER SELECTOR..DUPLOYAN DOUBLE MARK
	{0x1CF00, 0x1CF2D, prInCBExtend},    // Mn  [46] ZNAMENNY COMBINING MARK GORAZDO NIZKO S KRYZHEM ON LEFT..ZNAMENNY COMBINING MARK KRYZH ON LEFT
	{0x1CF30, 0x1CF46, prInCBExtend},    // Mn  [23] ZNAMENNY COMBINING TONAL RANGE MARK MRACHNO..ZNAMENNY PRIZNAK MODIFIER ROG
	{0x1D165, 0x1D166, prInCBExtend},    // Mc   [2] MUSICAL SYMBOL COMBINING STEM..MUSICAL SYMBOL COMBINING SPRECHGESANG STEM
	{0x1D167, 0x1D169, prInCBExtend},    // Mn   [3] MUSICAL SYMBOL COMBINING TREMOLO-1..MUSICAL SYMBOL COMBINING TREMOLO-3
	{0x1D16D, 0x1D172, prInCBExtend},    // Mc   [6] MUSICAL SYMBOL COMBINING AUGMENTATION DOT..MUSICAL SYMBOL COMBINING FLAG-5
	{0x1D17B, 0x1D182, prInCBExtend},    // Mn   [8] MUSICAL SYMBOL COMBINING ACCENT..MUSICAL SYMBOL COMBINING LOURE
	{0x1D185, 0x1D18B, prInCBExtend},    // Mn   [7] MUSICAL SYMBOL COMBINING DOIT..MUSICAL SYMBOL COMBINING TRIPLE TONGUE
	{0x1D1AA, 0x1D1AD, prInCBExtend},    // Mn   [4] MUSICAL SYMBOL COMBINING DOWN BOW..MUSICAL SYMBOL COMBINING SNAP PIZZICATO
	{0x1D242, 0x1D244, prInCBExtend},    // Mn   [3] COMBINING GREEK MUSICAL TRISEME..COMBINING GREEK MUSICAL PENTASEME
	{0x1DA00, 0x1DA36, prInCBExtend},    // Mn  [55] SIGNWRITING HEAD RIM..SIGNWRITING AIR SUCKING IN
	{0x1DA3B, 0x1DA6C, prInCBExtend},    // Mn  [50] SIGNWRITING MOUTH CLOSED NEUTRAL..SIGNWRITING EXCITEMENT
	{0x1DA75, 0x1DA75, prInCBExtend},    // Mn       SIGNWRITING UPPER BODY TILTING FROM HIP JOINTS
	{0x1DA84, 0x1DA84, prInCBExtend},    // Mn       SIGNWRITING LOCATION HEAD NECK
	{0x1DA9B, 0x1DA9F, prInCBExtend},    // Mn   [5] SIGNWRITING FILL MODIFIER-2..SIGNWRITING FILL MODIFIER-6
	{0x1DAA1, 0x1DAAF, prInCBExtend},    // Mn  [15] SIGNWRITING ROTATION MODIFIER-2..SIGNWRITING ROTATION MODIFIER-16
	{0x1E000, 0x1E006, prInCBExtend},    // Mn   [7] COMBINING GLAGOLITIC LETTER AZU..COMBINING GLAGOLITIC LETTER ZHIVETE
	{0x1E008, 0x1E018, prInCBExtend},    // Mn  [17] COMBINING GLAGOLITIC LETTER ZEMLJA..COMBINING GLAGOLITIC LETTER HERU
	{0x1E01B, 0x1E021, prInCBExtend},    // Mn   [7] COMBINING GLAGOLITIC LETTER SHTA..COMBINING GLAGOLITIC LETTER YATI
	{0x1E023, 0x1E024, prInCBExtend},    // Mn   [2] COMBINING GLAGOLITIC LETTER YU..COMBINING GLAGOLITIC LETTER SMALL YUS
	{0x1E026, 0x1E02A, prInCBExtend},    // Mn   [5] COMBINING GLAGOLITIC LETTER YO..COMBINING GLAGOLITIC LETTER FITA
	{0x1E08F, 0x1E08F, prInCBExtend},    // Mn       COMBINING CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
	{0x1E130, 0x1E136, prInCBExtend},    // Mn   [7] NYIAKENG PUACHUE HMONG TONE-B..NYIAKENG PUACHUE HMONG TONE-D
	{0x1E2AE, 0x1E2AE, prInCBExtend},    // Mn       TOTO SIGN RISING TONE
	{0x1E2EC, 0x1E2EF, prInCBExtend},    // Mn   [4] WANCHO TONE TUP..WANCHO TONE KOINI
	{0x1E4EC, 0x1E4EF, prInCBExtend},    // Mn   [4] NAG MUNDARI SIGN MUHOR..NAG MUNDARI SIGN SUTUH
	{0x1E5EE, 0x1E5EF, prInCBExtend},    // Mn   [2] OL ONAL SIGN MU..OL ONAL SIGN IKIR
	{0x1E6E3, 0x1E6E3, prInCBExtend},    // Mn       TAI YO SIGN UE
	{0x1E6E6, 0x1E6E6, prInCBExtend},    // Mn       TAI YO SIGN AU
	{0x1E6EE, 0x1E6EF, prInCBExtend},    // Mn   [2] TAI YO SIGN AY..TAI YO SIGN ANG
	{0x1E6F5, 0x1E6F5, prInCBExtend},    // Mn       TAI YO SIGN OM
	{0x1E8D0, 0x1E8D6, prInCBExtend},    // Mn   [7] MENDE KIKAKUI COMBINING NUMBER TEENS..MENDE KIKAKUI COMBINING NUMBER MILLIONS
	{0x1E944, 0x1E94A, prInCBExtend},    // Mn   [7] ADLAM ALIF LENGTHENER..ADLAM NUKTA
	{0x1F3FB, 0x1F3FF, prInCBExtend},    // Sk   [5] EMOJI MODIFIER FITZPATRICK TYPE-1-2..EMOJI MODIFIER FITZPATRICK TYPE-6
	{0xE0020, 0xE007F, prInCBExtend},    // Cf  [96] TAG SPACE..CANCEL TAG
	{0xE0100, 0xE01EF, prInCBExtend},    // Mn [240] VARIATION SELECTOR-17..VARIATION SELECTOR-256
}
